### ISSUE TITLE
AgGrid -> grid.clickOnSort() is failing with an exception "org.openqa.selenium.NoSuchElementException: could not find div, that has class ag-center-cols-viewport" . 

### ISSUE THREAD

**Issue by rohitkashyapvatta** [loyada/dollarx#40]
The version of AgGrid 19.0 is used in the application.

**Comment by loyada** [comment]
Stack trace:
at com.github.loyada.jdollarx.InBrowserFinder.find(InBrowserFinder.java:34)
at com.github.loyada.jdollarx.InBrowser.find(InBrowser.java:49)
at com.github.loyada.jdollarx.Operations$ScrollElement.toLeftCorner(Operations.java:522)
at com.github.loyada.jdollarx.singlebrowser.AgGrid.getVisibleHeaderPath(AgGrid.java:252)

This is likely related to the old ag-grid layout .

**Comment by loyada** [comment]
should be fixed

**Comment by ah3548** [comment]
AGGrid 20 Maybe still an issue?
