### ISSUE TITLE
error in image processing

### ISSUE THREAD

**Issue by loyada** [loyada/dollarx#85]
java.lang.ClassCastException: class java.lang.Double cannot be cast to class java.lang.Long (java.lang.Double and java.lang.Long are in module java.base of loader 'bootstrap')

	at com.github.loyada.jdollarx.visual.Images.getVisiblePageOffset(Images.java:446)
	at com.github.loyada.jdollarx.visual.Images.captureImage(Images.java:502)

**Comment by loyada** [comment]
Fixed
